### ISSUE TITLE
Comma appearing in authors section of META.json

### ISSUE THREAD

**Issue by vti** [tokuhirom/Minilla#153]
Having this POD:
```
=head1 AUTHOR

Viacheslav Tykhanovskyi, E<lt>viacheslav.t@gmail.comE<gt>
```

after doing `minil dist` I get in META.json:
```
   "author" : [
      ", Viacheslav Tykhanovskyi"
   ],
```

**Comment by tokuhirom** [comment]
This is a bug.

**Comment by tokuhirom** [comment]
Hmm... The issue doesn't reproduce on my environment.
Could you update CPAN::Meta and Minilla?

**Comment by vti** [comment]
I have the latest Minilla. Maybe it's because of my `git` setup? I have `vti` there instead of my name. When author was `vti <email>` then everything was ok.

**Comment by tokuhirom** [comment]
Hmm. I can't reproduce this issue. Could you send me a test code?

**Comment by vti** [comment]
Yeah, I will try to create a minimal dist.

**Comment by avkhozov** [comment]
@tokuhirom I have similar problem. You can see it at https://github.com/avkhozov/test-mojo-session repo. ``META.json`` is ok, but on ``metacpan`` https://metacpan.org/release/test-mojo-session in contributors section I see ``Andrey Khozov, C.``

In ``pod`` section:
```perl
=head1 AUTHOR

Andrey Khozov, C<avkhozov@googlemail.com>.
```

**Comment by vti** [comment]
I have found the problem. I had two POD blocks LICENSE and LICENSE AND COPYRIGHT. As soon as I removed one of them comma disappeared and email was added.
