### ISSUE TITLE
RFC: config key to use alternative to Pod::Markdown

### ISSUE THREAD

**Issue by felliott** [tokuhirom/Minilla#161]
Hey @tokuhirom,

Would you be interested in a patch to add a config key to use Pod::Markdown::Github in place of Pod::Markdown?  I'll be happy to write it up, if so.  Thank you!

Cheers,
Fitz

**Comment by tokuhirom** [comment]
What's the difference between these two modules?

**Comment by amarnus** [comment]
The only thing `Pod::Markdown::Github` does is to allow the Perl code snippets in the `README.md` file generated by Minilla to be syntax highlighted when viewed on github.com. The module itself inherits from `Pod::Markdown`.

**Comment by tokuhirom** [comment]
Hm. Okay, I can merge the modification. Please sent me p-r.

**Comment by felliott** [comment]
Will do.  Thank you!

Cheers,
Fitz
