### ISSUE TITLE
Allow overriding minimum Perl version

### ISSUE THREAD

**Issue by kentfredric** [tokuhirom/Minilla#167]
https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm#L89   # Forces 5.8.1

https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/ModuleMaker/ModuleBuild.pm#L73  # Forces 5.8.1

https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/ModuleMaker/ModuleBuildTiny.pm#L102    # Forces 5.8.1 

Users who wish to go higher or lower than this, should be able to.

**Comment by kentfredric** [comment]
Also: 

- https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/Profile/ExtUtilsMakeMaker.pm#L38
- https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/Profile/ModuleBuild.pm#L38
- https://metacpan.org/source/TOKUHIROM/Minilla-v2.4.1/lib/Minilla/Profile/ModuleBuildTiny.pm#L38

I'm not sure exactly how/why perl-version is getting forced here in META.json

**Comment by miyagawa** [comment]
Copying the same comment: Build files generated by Minilla, be it Module::Build or Module::Build::Tiny (now the default) ends up using CPAN::Meta in the configure time, and CPAN::Meta requires 5.8.1.

**Comment by miyagawa** [comment]
In 58fbdf34fbec20b6666fc461fb40ae2537574428 there's a workaround to support older perl by avoiding CPAN::Meta (which requires 5.8). The commit message says 5.8.4, but I guess this applies to 5.6 use as well.

Personally I don't mind requiring Minilla generated distribution to require 5.8, if that makes maintaining Minilla complicated. It's a tool by @tokuhirom so he has the right to reject them, and if you have to end up maintaining a module that requires exotic runtime such as 5.6, you can use other tools.

**Comment by ribasushi** [comment]
> Personally I don't mind requiring Minilla generated distribution to require 5.8, 

+1. There is nothing wrong with an authoring tool making a statement (in fact this is arguably their purpose)

**Comment by karenetheridge** [comment]
I'm okay with making statements as long as the users understand what statements they are buying into by virtue of using the tool.
