### ISSUE TITLE
The code to get the repository URL fails on some locales 

### ISSUE THREAD

**Issue by jluis** [tokuhirom/Minilla#176]
I discovered this issue, and Minilla distribution, during this October CPAN pull request where I was assigned Redis::Fast.
One of the claims of Minilla is that it leaves the repository "cpanm $git_URL" ready.
I'm preparing an PR to change $ENV{LANG} to C and back after the backtics

**Comment by syohex** [comment]
Could you show us output of `git remote show -n origin` in such locale ?

**Comment by jluis** [comment]
In my locale ca_ES.UTF-8
<---Start--->
    * remot origin
      URL d'obtenció: https://github.com/tokuhirom/Minilla.git
      URL de pujada: https://github.com/tokuhirom/Minilla.git
      Branca de HEAD: (not queried)
      Branques remotes: (estat no consultat)
       develop
       feature/module_maker
       feature/no-context
       feature/requires_external_bin
       feature/script_files
       issue/45-allow_pureperl
       issue/54-use-module-metadata
       master
        mbt
        modulebuildtiny
      Branca local configurada per a 'git pull':
       master es fusiona amb el remot master
      Referència local configurada per a 'git push' (estat no consultat):
       (coincident) puja a (coincident)
<---End--->

I checked also the *.po files in the git git and looks like the regex could be write </URL[^:]*: (.*)$/m> and if shoud work for all localitzations but zn_CN (Chinese China) and bg (Bulgarian)

**Comment by syohex** [comment]
#177 was merged.
