### ISSUE TITLE
cpan-outdated lists Minilla's latest version at 2.5.0

### ISSUE THREAD

**Issue by GeJ** [tokuhirom/Minilla#178]
It seems that there was a 2.5.0 version pushed on CPAN after 2.4.2. Since then, 2.4.3 and 2.4.4 won't show up on the output of cpan-outdated.

It's not exactly an issue with Minilla's code, but I believe only Matsuno-san can fix this annoying detail either by releasing a 2.5.1 Minilla or removing 2.5.0 from PAUSE (the second option is pure speculation on my side since I have no experience with PAUSE and/or releasing a distribution).

Thanks in advance for considering this.

**Comment by tokuhirom** [comment]
Shippded minil 3.0.0!
