### ISSUE TITLE
build with ModuleBuild tool doesn't install dependencies

### ISSUE THREAD

**Issue by JForst** [tokuhirom/Minilla#189]
Hi,
it seems that [this commit](https://github.com/tokuhirom/Minilla/commit/4fd3815b3c1259d90f56020c476b2845896dabb1) did break the installation with cpanm of pakets which use ModuleBuild in that sort, that dependencies noted in cpanfile are no longer installed, due to the lack of MYMETA files.

I generated a small tarball, which is not installable with cpanm if the dependency (here Moose) is not already installed.

The tarball is generated with the following steps:

- minil new -p ModuleBuild Foo
- add requires 'Moose'; to cpanfile
- add use Moose; to Foo.pm
- minil dist
- cpanm Foo-0.01.tar.gz  # fails

if  lib/Minilla/ModuleMaker/ModuleBuild.pm lines 139 .. are inserted again, all works like expected. That means running

- minil dist
- cpanm Foo-0.01.tar.gz # installs Moose as dependency

Kind regards,

Jörg

**Comment by karenetheridge** [comment]
I can't reproduce this issue.  The new prereqs added to cpanfile do make it into META.yml and META.json in the built distribution, so they should be properly satisfied by any cpan client installing the distribution.

**Comment by Leont** [comment]
Can you tell me *exactly* which MB versions you're observing this with? I wouldn't be surprised if that `0.4005` really ought to be `0.4200`

**Comment by JForst** [comment]
Yes, you are right, the prereqs do appear in META.yml and META.json,
but the Build.PL file does not contain the part where these files
were copied to MYMETA.yml and MYMETA.json.

But without MYMETA.yml and MYMETA.json Module::Build doesn't install the
dependencies.

**Comment by JForst** [comment]
My MB version is 0.4214

**Comment by Leont** [comment]
> But without MYMETA.yml and MYMETA.json Module::Build doesn't install the dependencies.

Module::Build **creates** the MYMETA files when you do «perl Build.PL», the whole copying thing paves over that.

It seems Minilla doesn't write the prerequisites to the Build.PL, and doesn't run anything else that pulls them out of the cpanfile either. The current situation isn't correct, but I don't think that reverting to the old one is the solution either.

**Comment by karenetheridge** [comment]
One option is simply to drop support for Module::Build altogether. These days if a distribution *needs* Module::Build, it is complicated enough that it wouldn't be using Minilla anyway.

**Comment by Leont** [comment]
> One option is simply to drop support for Module::Build altogether. These days if a distribution needs Module::Build, it is complicated enough that it wouldn't be using Minilla anyway.

I don't think that's an option for some of the dists that use Minilla (in particular the xsutil ones)

**Comment by JForst** [comment]
>    It seems Minilla doesn't write the prerequisites to the Build.PL, and
>    doesn't run anything else that pulls them out of the cpanfile either. The
>    current situation isn't correct, but I don't think that reverting to the
>    old one is the solution either.

How do these prerequisites have to look like? Sorry I'm not experienced in
the details of package building.

In the Build.PL of Module::Build there is also the fallback of copying 
META files to MYMETA, so why is this wrong?

**Comment by Leont** [comment]
> How do these prerequisites have to look like? Sorry I'm not experienced in the details of package building.

Something like [this](https://metacpan.org/source/LEONT/File-Map-0.34/Build.PL#L14).

> In the Build.PL of Module::Build there is also the fallback of copying META files to MYMETA, so why is this wrong?

It only does that when there is no MYMETA file, and unlike other dists it actually has good (bootstrapping) reasons why that may be the case (though I don't think it's actually necessary).

**Comment by JForst** [comment]
So, generating a more complete Build.PL file should work. I tried to do so [here](https://github.com/JForst/Minilla/commit/d12ec03b5ec79773524fd3312350dc82f69d8b88).

Did I miss something?
