### ISSUE TITLE
Minilla gets confused with perl version with v5.xx form

### ISSUE THREAD

**Issue by GeJ** [tokuhirom/Minilla#198]
In my module, I included a :

use v5.20;

Upon issuing a new `minil release`, Minilla set the prereq->runtime->requires->perl to "5.20"

When trying to install my distribution, cpanm complained that it required perl 5.20 and that I only had 5.020003.

All this time, Minilla seemed to ignore what I put in cpanfile.

Is this normal? Is there something wrong with 'use v5.20;' that I overlooked?

**Comment by syohex** [comment]
> All this time, Minilla seemed to ignore what I put in cpanfile.

No, Minilla does not ignore `version` in cpanfile. Merge both version by `CPAN::Meta::Prereqs` and uses higher version of them.

**Comment by GeJ** [comment]
You're correct, my apologies, it was badly phrased.

I did a little digging yesterday (I still need to double-check that I haven't missed something important somewhere else) but it looks like `Minilla::Metadata#_extract_perl_version()` does a very basic job at getting the required perl version. Should I work on this part?

What about 'normalizing' the version with something like `version->parse($value_found_in_source)->normal` ?
Does it look like an acceptable solution?
