### ISSUE TITLE
How to bundle text files with library

### ISSUE THREAD

**Issue by kidambisrinivas** [tokuhirom/Minilla#214]
How do I bundle text files with a library so that when I install with cpanm or carton, I get the text file in the same path.

Example library like this: https://github.com/gisle/mozilla-ca/tree/master/lib/Mozilla/CA

**Comment by syohex** [comment]
It is enough to `git add`. You can check by MANIFEST file which is generated by `minil build`.

**Comment by skaji** [comment]
Put them in `share` directory, and use https://metacpan.org/pod/File::ShareDir

**Comment by kidambisrinivas** [comment]
Yes, the File::Share solution worked for me

https://metacpan.org/pod/File::Share

Thanks

**Comment by cxw42** [comment]
@kidambisrinivas Would you be willing to share your solution?  I am using the ExtUtils::MakeMaker profile.  I see that I can use [File::ShareDir::Install](https://metacpan.org/pod/File::ShareDir::Install) in `Makefile.PL` to copy the share files.  However, I do not see how to tell Minilla to use File::ShareDir::Install.  Also, I do not see instructions in the generated `Makefile` to copy the files.  Do I need to create a `Share.PL` file or something?  Or is `install_share` not supported with EUMM?  Thank you!
