### ISSUE TITLE
c_source is set for pure-Perl packages

### ISSUE THREAD

**Issue by ppisar** [tokuhirom/Minilla#235]
KAZUHO/Server-Starter-0.34 CPAN distribution uses Minilla to generate Build.PL. Although the distribution does not have any XS module and does not need a C compiler, Module::Build insists on a compiler.

The reason is that Minilla adds:

~~~
c_source => [qw()],
~~~

and that makes Module::Build to require a compiler.

I reported a bug against Module::Build to handle empty list as undef [https://rt.cpan.org/Public/Bug/Display.html?id=124625] but it would be great if Minilla stopping defining c_source if there is no XS module.

**Comment by skaji** [comment]
Thanks for reporting this. I will fix this next Sunday.
