### ISSUE TITLE
META.yml author information can get misread from POD

### ISSUE THREAD

**Issue by jmacdotorg** [tokuhirom/Minilla#240]
I have a module that offers an object method `author()`, so its POD has a section that looks like this:

```
=head3 author

 $author = $wm->author;

Method description goes here, blah blah blah...
```

As a result of this, the following ends up in the distribution's META.yml file:

```
   "author" : [
      "$author = $wm->author;"
   ],
```

Minilla (or something Minilla uses) seems a bit too lax with POD-parsing here. Perhaps it should extract meaning only from `=head1 AUTHOR`, and not any heading named "author" with any casing?

**Comment by skaji** [comment]
Should be fixed in https://metacpan.org/release/SKAJI/Minilla-v3.0.18
