### ISSUE TITLE
Versions are updated in not indexed files

### ISSUE THREAD

**Issue by vti** [tokuhirom/Minilla#256]
Inside of `t/` directory I have a test file with `our $VERSION = '123'` inside. When trying to release with Minilla that version is updated too, even though `t/` directory is in `no_index` list. I think that skipping unindexed would prevent this from happening and actually makes sense, since those file won't be indexed by CPAN anyway.

**Comment by vti** [comment]
Using `# No BumpVersion` helps, but it probably makes sense to ignore specific directories.

**Comment by skaji** [comment]
@vti Could you check #257 ?

**Comment by vti** [comment]
@skaji works!
