### ISSUE TITLE
On Cygwin, {{$NEXT}} isn't found in DOS-format Changes file

### ISSUE THREAD

**Issue by cxw42** [tokuhirom/Minilla#259]
I am experimenting with migrating an older distribution that uses CRLF line endings.  `minil release` gave me `No mention of {{$NEXT}} in changelog file 'Changes'`, even though `{{$NEXT}}` was the only thing on a line.  I changed the `Changes` file to LF line endings, and `minil` was then able to find `{{$NEXT}}` and proceed.

**Comment by syohex** [comment]
Close by #264
