### ISSUE TITLE
Don't color the console messages (or with better colours)

### ISSUE THREAD

**Issue by wollmers** [tokuhirom/Minilla#277]
On my first use of the latest version

  ` ` `
$ minil migrate
$ minil test
 ` ` `

I got light blue messages on white background. That's very hard and nearly impossible to read.

So please don't colour normal messages and let the user settings of the terminal do their work. Others like `Dist::Milla` only use red e. g. for failed tests (maybe via `Dist::Zilla` or whatever), or also e. g. `systemd` on a standard installation of Debian.

**Comment by skaji** [comment]
patches are welcome

**Comment by skaji** [comment]
Ah, minil already has `--no-color` option.
