### ISSUE TITLE
license not reflected in POD/README.md

### ISSUE THREAD

**Issue by srchulo** [tokuhirom/Minilla#282]
I set `license` in my `minil.toml`:

```
license="restricted"
```

And this updates it in `META.json` and `META.yml`, but the license in the POD, the `README.md`, and the `LICENSE` file are all still the PERL5 license.

Is this the intended behavior? If it's not possible to make these changes after the fact, maybe an option could be allowed to be provided to `minil new`?

**Comment by syohex** [comment]
> Is this the intended behavior? 

Yes. It is not bug.

**Comment by srchulo** [comment]
Okay, thanks!
