### ISSUE TITLE
Support for gitlab badges

### ISSUE THREAD

**Issue by srchulo** [tokuhirom/Minilla#285]
I was wondering if you would consider adding or accepting a pull request for Gitlab badges?

https://docs.gitlab.com/ee/user/project/pipelines/settings.html#pipeline-badges

They have two-- pipeline and coverage, so I don't know if you would add both if `gitlab` was listed in badges, or if you would need two identifiers, like `gitlab-pipeline` and `gitlab-coverage`.

**Comment by skaji** [comment]
Sounds good. PRs are welcome.
