### ISSUE TITLE
Mention --with-recommends in the INSTALLING section of the POD

### ISSUE THREAD

**Issue by akarelas** [tokuhirom/Minilla#293]
`minil release` will not run if Minilla was installed with just `cpanm Minilla` as https://metacpan.org/pod/distribution/Minilla/lib/Minilla/Tutorial.pod#Installing suggests.

`cpanm --with-recommends Minilla` makes `minil release` work better.

So I suggest that the INSTALLING section mentions `--with-recommends` in the `cpanm` command.

**Comment by skaji** [comment]
Yeah. We will be happy to accept a document patch for it.

**Comment by akarelas** [comment]
Is a PR really needed?

Wouldn't it be faster and easier for all of us if you just added the string `"--with-recommends"` with your editor at the right place?

Shouldn't we try to make life easier for everyone if possible?

Thanks

**Comment by syohex** [comment]
Closed by #294
