### ISSUE TITLE
Not detecting version in Changes file

### ISSUE THREAD

**Issue by mlawren** [tokuhirom/Minilla#59]
Minilla git version 74db0dba0314af6a9c20c2494694737283d61425:

    No mention of version '0.80.1_2' in changelog file 'Changes'
    Edit file? [y] 
    No mention of version '0.80.1_2' in changelog file 'Changes'
    Edit file? [y] ^Z
    [2]+  Stopped                 minil release
    mark@lifebook:~/src/sys-cmd$ grep '0.80.1_2' Changes 
    0.80.1_2 (2013-05-18)

The `Changes` file contains the new version but minilla doesn't seem to see it. I suspect that minilla is only looking at the git index version. Perhaps after editing the file it wants to automatically add Changes to the index?

**Comment by syohex** [comment]
Please reopen if you still have problem.
